FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY config ./config
COPY frontend ./frontend

ENV PYTHONPATH=/app

EXPOSE 8501

CMD streamlit run frontend/app.py --server.port=8501 --server.address=0.0.0.0
